@startuml

browser --> browser: 进入登录页面及获取验证码开始

browser -> Server: 1/login.html
Server --> browser: 1.1 /login.html
browser -> ValidateCodeController: 1.2 /code/sms?mobile=10123456789
browser -> ValidateCodeController: 1.3 /code/image

ValidateCodeController --> ValidateCodeController: 2. createCode()
ValidateCodeController -> AbstractValidateCodeProcessor: 2.1 findValidateCodeProcessor()

AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 2.2 produce()
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 2.2.1 generate()
AbstractValidateCodeProcessor -> ValidateCodeGenerator: 2.2.1.1 getValidateCodeGenerator()

ValidateCodeGenerator --> ValidateCodeGenerator: 2.2.1.2generate()
ValidateCodeGenerator --> AbstractValidateCodeProcessor: 2.2.1.3 code

AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 2.2.2 saveSession()
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 2.2.3 send()
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 2.2.3 send()
AbstractValidateCodeProcessor --> browser: 2.2.3.1 如果为图片类型，返回图片
AbstractValidateCodeProcessor -> SmsCodeSender: 2.2.3.1 如果为短信类型

SmsCodeSender --> SmsCodeSender: 2.2.3.2 sendSms

browser --> browser: 进入登录页面及获取验证码结束

@enduml