@startuml

browser --> browser: OAuth2登录注册流程开始

browser -> SocialAuthenticationFilter: 1 跳转到 \n/Authentication/social

SocialAuthenticationFilter -> SocialAuthenticationSignUpFilter: 1.1 doFilter()
SocialAuthenticationSignUpFilter --> SocialAuthenticationSignUpFilter: 1.2\n attemptAuthService()
SocialAuthenticationSignUpFilter -> ProviderManager: 1.2.1\n authenticate(authRequest)
ProviderManager -> SocialAuthenticationSignUpProvider: 1.2.1.1\n authenticate(token)
SocialAuthenticationSignUpProvider --> SocialAuthenticationSignUpProvider: 1.2.1.1.1\n authenticate(token)
SocialAuthenticationSignUpProvider -> SocialOAuth2AuthenticationService: 1.2.1.1.1.1\n user=loadUserByUserId(id)

SocialOAuth2AuthenticationService --> SocialAuthenticationSignUpProvider: 1.2.1.1.2\n user!=null
SocialAuthenticationSignUpProvider --> ProviderManager: 1.2.1.2 抛出\n RegisterUserFailureException\n("Username used")
ProviderManager --> SocialAuthenticationSignUpFilter: 1.2.2 抛出\n RegisterUserFailureException\n("Username used")
SocialAuthenticationSignUpFilter --> SocialAuthenticationSignUpFilter: 1.2.2 抛出\n RegisterUserFailureException\n("Username used")
SocialAuthenticationSignUpFilter -> SocialAuthenticationFailureHandler: 1.3 抛出\n RegisterUserFailureException\n("Username used")
SocialAuthenticationFailureHandler --> browser: 1.4 根据LoginType类型\n返回 JSON 或 HTML 格式的错误信息

SocialOAuth2AuthenticationService --> SocialAuthenticationSignUpProvider: 1.2.1.1.2\n user=null
SocialAuthenticationSignUpProvider -> SocialOAuth2AuthenticationService: 1.2.1.1.2.1\n user=registerUser()
SocialOAuth2AuthenticationService -> ProviderSignInUtils: 1.2.1.1.2.1.1\n doPostSignUp()
ProviderSignInUtils -> OAuthJdbcUsersConnectionRepository: 1.2.1.1.2.1.1.1\n addConnection()
OAuthJdbcUsersConnectionRepository --> ProviderSignInUtils: 1.2.1.1.2.1.2 返回
ProviderSignInUtils --> SocialOAuth2AuthenticationService: 1.2.1.1.2.2 返回
SocialOAuth2AuthenticationService --> SocialAuthenticationSignUpProvider: 1.2.1.1.3\n 返回user
SocialOAuth2AuthenticationService --> ProviderManager: 1.2.1.3\n 返回user
ProviderManager --> SocialAuthenticationSignUpFilter: 1.2.3 返回user
SocialAuthenticationSignUpFilter --> browser: 1.5 注册成功能，\n返回 RedirectUrl 或 \nDefaultSuccessUrl

browser --> browser: OAuth2登录注册流程结束

@enduml