@startuml

browser --> browser: 手机短信验证码登录流程开始

browser -> ValidateCodeFilter: /authentication/mobile

ValidateCodeFilter --> ValidateCodeFilter: 1. doFilterInternal(),\n 验证码逻辑
ValidateCodeFilter -> ValidateCodeType: 1.1 getValidateCodeType(), \n如果图片与短信都适用此 uri，
ValidateCodeType --> ValidateCodeFilter: ValidateCodeType,\n 优先使用短信验证码逻辑
ValidateCodeFilter -> AbstractValidateCodeProcessor: 1.2 findValidateCodeProcessor\n(ValidateCodeType)

AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.3 validate(request)
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.3.1 从 session 获取验证码
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.3.2 从 request 获取验证码
AbstractValidateCodeProcessor --> ValidateCodeFilter: 1.3.3 校验成功，\n删除 session中的验证码

AbstractValidateCodeProcessor --> ValidateCodeFilter: 1.3.3 校验失败，\n抛出 ValidateCodeException
ValidateCodeFilter -> BrowserAuthenticationFailureHandler: 1.4 校验失败，\n抛出 ValidateCodeException
BrowserAuthenticationFailureHandler --> browser: 1.4.1 onAuthenticationFailure()\n根据设置的 LoginType \n返回 JSON 或者 HTML 格式

ValidateCodeFilter -> SmsCodeAuthenticationFilter: 1.4.2 校验成功.\n doFilter()
SmsCodeAuthenticationFilter --> SmsCodeAuthenticationFilter: 1.4.2.1 attemptAuthentication()
SmsCodeAuthenticationFilter --> SmsCodeAuthenticationFilter: 1.4.2.1.1 SmsCodeAuthenticationToken()
SmsCodeAuthenticationFilter -> AuthenticationManager: 1.4.2.1.2 authenticate(token)

AuthenticationManager -> SmsCodeAuthenticationProvider: 1.4.2.1.2.1 getProvider
SmsCodeAuthenticationProvider --> SmsCodeAuthenticationProvider: 1.4.2.1.2.2 authenticate(token)
SmsCodeAuthenticationProvider -> UserDetailsService: 1.4.2.1.2.2.1 getUserDetailsService()

UserDetailsService --> UserDetailsService: 1.4.2.1.2.2.1.1 loadUserByUsername(username)
UserDetailsService --> UserDetailsService: 1.4.2.1.2.2.1.2 如果返回 null, 用户未注册
UserDetailsService --> UserDetailsService: 1.4.2.1.2.2.1.3 registerUser()，自动注册

UserDetailsService --> SmsCodeAuthenticationProvider: 1.4.2.1.2.2.1 如果返回 user 或\n 自动注册后返回 user
SmsCodeAuthenticationProvider --> AuthenticationManager: 1.4.2.1.2.2 校验成功，\n返回 Authentication

AuthenticationManager --> SmsCodeAuthenticationFilter: 1.4.2.1.3 校验成功，\n返回 Authentication
SmsCodeAuthenticationFilter --> AbstractValidateCodeProcessor: 1.4.2.1 校验成功，\n返回 Authentication
AbstractValidateCodeProcessor --> ValidateCodeFilter: 1.4.3 校验成功，\n返回 Authentication

ValidateCodeFilter --> browser: 1.4.4.1 返回 RedirectUrl \n或 DefaultSuccessUrl

UserDetailsService --> SmsCodeAuthenticationProvider: 1.4.2.1.2.2.1 抛出异常
SmsCodeAuthenticationProvider --> AuthenticationManager: 1.4.2.1.2.2 校验失败，抛出异常

AuthenticationManager --> SmsCodeAuthenticationFilter: 1.4.2.1.3 校验失败，抛出异常
SmsCodeAuthenticationFilter --> ValidateCodeFilter: 1.4.3 校验失败，抛出异常
ValidateCodeFilter -> BrowserAuthenticationFailureHandler: 1.4.4 转交\nBrowserAuthenticationFailureHandler\n处理
BrowserAuthenticationFailureHandler --> browser: 1.4.4.2 返回 login.html

browser --> browser: 手机短信验证码登录流程结束

@enduml