@startuml

browser --> browser: 进入登录页面及获取验证码开始

browser -> Server: /login.html
Server --> browser: /login.html
browser -> ValidateCodeController: /code/sms?mobile=10123456789
browser -> ValidateCodeController: /code/image

ValidateCodeController --> ValidateCodeController: 1. createCode()
ValidateCodeController -> AbstractValidateCodeProcessor: 1.1 findValidateCodeProcessor()

AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.2 produce()
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.2.1 generate()
AbstractValidateCodeProcessor -> ValidateCodeGenerator: 1.2.1.1 getValidateCodeGenerator()

ValidateCodeGenerator --> ValidateCodeGenerator: generate()
ValidateCodeGenerator --> AbstractValidateCodeProcessor: code

AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.2.2 saveSession()
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.2.3 send()
AbstractValidateCodeProcessor --> AbstractValidateCodeProcessor: 1.2.3 send()
AbstractValidateCodeProcessor --> browser: 1.2.3.1 如果为图片类型，返回图片
AbstractValidateCodeProcessor -> SmsCodeSender: 1.2.3.1 如果为短信类型

SmsCodeSender --> SmsCodeSender: 1.2.3.2 sendSms

browser --> browser: 进入登录页面及获取验证码结束

@enduml