@startuml

skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF
ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor #00897b
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF
ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}
participant "SocialCoreConfig"  #1565c0
participant "RememberMeConfigurerAware"  #1565c0

participant "BaseSocialConfigurerAdapter"  #1565c0

participant "SecurityCoreConfigurer" #1565c0
SecurityCoreConfigurer -> SecurityCoreConfigurer: 安全配置流程开始
note right SecurityCoreConfigurer: 基本配置:\n SecurityCoreConfigurer: \n\
 social模块 SocialConfiguration\n core模块 SecurityConfiguration\n\
               ValidateCodeBeanConfiguration\n               SecurityRememberMeConfiguration\n\
               PropertiesConfiguration\n\                SecuritySessionConfiguration\n\
               SecurityCsrfConfiguration\n\                UriAuthorizeConfiguration\n\
               UriAuthorizeWebMvcConfigurer
alt afterPropertiesSet
RememberMeConfigurerAware --> RememberMeConfigurerAware: 1 afterPropertiesSet()
RememberMeConfigurerAware --> RememberMeConfigurerAware: 1.1 检查数据库是否存在\n persistent_logins\n session表\没有创建\n有就什么都不做
end
activate SecurityCoreConfigurer
opt preConfigure
SecurityCoreConfigurer --> SecurityCoreConfigurer: 2 groupingAuthorizeRequestUris(..)\n 对所有的AuthorizeRequestUris\n 按权限进行分类，放入 Map
activate SecurityCoreConfigurer
participant "HttpSecurityAware" #1565c0
SecurityCoreConfigurer -> HttpSecurityAware: 2.1 对所有的\nHttpSecurityAware\n进行遍历
activate HttpSecurityAware
note right : 实现类:\n\
SmsCodeLoginAuthenticationConfigurerAware\n\
ValidateCodeConfigurerAware\n\
SocialSecurityConfigurerAware\n\
SocialAuthenticationSignUpConfigurerAware\n\
RememberMeConfigurerAware\n\
SessionConfigurerAware\n\
ClientConfigurerAware\n\
CsrfConfigurerAware
HttpSecurityAware -> HttpSecurity: 2.1.1 preConfigure(http)
activate HttpSecurity
HttpSecurity --> HttpSecurity: 2.1.2 http.apply(config)\n这里对所有的\n config进行配置
note right : SmsCodeLoginAuthenticationConfig\n\
SocialAuthenticationSignUpConfig\n\
SocialCoreConfig
HttpSecurity --> HttpSecurityAware: 2.1.3 把HttpSecurityAware中\n所有的AuthorizeRequestUris\n 按权限进行分类，放入对应的 Set\n包括SecurityCoreConfigurer中
deactivate HttpSecurity
HttpSecurityAware --> SecurityCoreConfigurer: 2.1.4 返回
end
deactivate HttpSecurityAware
deactivate SecurityCoreConfigurer
opt http.formLogin等配置
SecurityCoreConfigurer -> HttpSecurity: 3 http formLogin authorizeRequests logout csrf等配置
activate HttpSecurity
HttpSecurity --> HttpSecurity: .. 设置
HttpSecurity --> HttpSecurity: 3.1 antMatchers(..)\n对所有的AuthorizeRequestUris\n 已按权限分类的所有Set\n进行对应设置
note right : .antMatchers(permitAllArray).permitAll()\n\
.antMatchers(denyAllArray).denyAll()\n\
.antMatchers(anonymousArray).anonymous()\n\
.antMatchers(authenticatedArray).authenticated()\n\
.antMatchers(fullyAuthenticatedArray).fullyAuthent\n\
.antMatchers(rememberMeArray).rememberMe()
HttpSecurity --> HttpSecurity: .. 设置
HttpSecurity --> SecurityCoreConfigurer: 3.2 返回
end
deactivate HttpSecurity
activate SecurityCoreConfigurer
opt postConfigure
SecurityCoreConfigurer -> HttpSecurityAware: 4 对所有的\nHttpSecurityAware\n进行遍历
activate HttpSecurityAware
activate HttpSecurity
HttpSecurityAware -> HttpSecurity: 4.1 postConfigure(http)
HttpSecurity --> HttpSecurity: 4.2 http.apply(config)\n这里对所有的\n config进行配置
note right : SmsCodeLoginAuthenticationConfig\n\
SocialAuthenticationSignUpConfig\n\
SocialCoreConfig

HttpSecurityAware --> SecurityCoreConfigurer: 4.3 返回
end
deactivate HttpSecurity
deactivate HttpSecurityAware
deactivate SecurityCoreConfigurer

deactivate SecurityCoreConfigurer

SecurityCoreConfigurer -> SecurityCoreConfigurer: 安全配置流程结束

== API ==
opt 配置文件相关的 API
note over SecurityCoreConfigurer: 所有 HttpSecurity\n最终都通过此配置\n如非必要勿修改
note over HttpSecurityAware: 对 HttpSecurity 的配置\n推荐使用此接口\n实现此接口注入IOC容器即可

note over BaseSocialConfigurerAdapter: 第三方API\n 与 Social的适配器\n添加第三方登录API时继承
note over BaseSocialConfigurerAdapter: 目前有三个子类\nGiteeAutoConfiguration\nQqAutoConfiguration\nWeixinAutoConfiguration
note over SocialCoreConfig: social 核心配置最终通过\nSocialSecurityConfigurerAware\n配置，如非必要勿修改

end

@enduml