server:
  port: 9090

spring:
  profiles:
    active: dev
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ums?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # thymeleaf
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .htm
    servlet:
      content-type: text/html;charset=UTF-8
  # jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # session 简单配置
  session:
    # session 存储模式设置, 要导入相应的 spring-session 类的依赖, 默认为 none, 分布式服务应用把 session 放入 redis 等中间件
    store-type: none
    # session 过期时间
    timeout: PT300s

ums:
  client:
    # 登录页
    login-page: /login
    # 登录失败页
    failure-url: /login
    # 设置登录后返回格式(REDIRECT 与 JSON): 默认 JSON
    login-process-type: redirect
    # 设置处理登录表单的 uri，不需要用户实现此 uri，由 Spring security 自动实现， 默认为 /authentication/form
    login-processing-url: /authentication/form
    # 登录成功页
    success-url: /
    # 设置登出 url, 默认为 /logout
    logout-url: /logout
    # 设置登出后跳转的 url, 默认为 /login
    logout-success-url: /login
    # 设置登录时用户名的 request 参数名称, 默认为 username
    usernameParameter: username
    # 设置登录时用户密码的 request 参数名称, 默认为 password
    passwordParameter: password
    # 登录后是否利用 Referer 进行跳转, 默认为: true
    useReferer: true
    # 设置由客户端决定认证成功要跳转的 url 的 request 参数名称, 默认为 redirectTargetUrl
    targetUrlParameter: redirectTargetUrl
    # 不需要认证的静态资源 urls, 例如: /resources/**, /static/**
    ignoring-urls:
      - /static/**
    # 不需要认证的 uri(可以带 HttpMethod 后缀; 用:隔开), 例如: /user/** 或 /user/**:post, 默认为 空 Set.
    permit-urls:
      - /**/*.html:GET
      - /login2:GET

    # =============== login routing 功能: 解决跳转登录成功后不能跳转原始请求的问题 ===============

    # 是否开启根据不同的uri跳转到相对应的登录页, 默认为: false, 当为 true 时还需要配置 loginUnAuthenticationRoutingUrl 和 authRedirectSuffixCondition
    open-authentication-redirect: true
    # 当请求需要身份认证时，默认跳转的url 会根据 authJumpSuffixCondition 条件判断的认证处理类型的 url，默认实现 /authentication/require,
    # 当 openAuthenticationRedirect = true 时生效.
    login-un-authentication-routing-url: /authentication/require
    # 设置 uri 相对应的跳转登录页, 例如：key=/**: value=/login.html, 用等号隔开key与value, 如: /**=/login.html, 默认为空.
    # 当 openAuthenticationRedirect = true 时生效.
    # 支持通配符, 匹配规则： /user/aa/bb/cc.html 匹配 pattern：/us?r/**/*.html, /user/**, /user/*/bb/c?.html, /user/**/*.*.
    # 规则具体看 AntPathMatcher.match(pattern, path)
    auth-redirect-suffix-condition:
      - '/hello=/login2'
      - '/user/**=/login'
      - '/order/**=/login'
      - '/file/**=/login'
      - '/social/**=/signIn.html'

  # 验证码配置
  codes:
    # 验证码缓存类型, 默认: SESSION, 可选: REDIS/SESSION
    validate-code-cache-type: redis
    # 获取验证码的 url 的前缀, 默认: /code
    get-validate-code-url-prefix: /code
    # 图片验证码
    image:
      # 设置需要图片验证码认证的 uri(必须是非 GET 请求)，多个 uri 用 “-” 或 ","号分开支持通配符，如：/hello,/user/*；默认为 /authentication/form
      auth-urls:
        - /authentication/form
        - /authentication/social
      # 验证码长度
      length: 4
      height: 60
      width: 270
      expire: 180
      request-para-height-name: height
      request-para-width-name: width
      request-param-image-code-name: imageCode
    # 自定义滑块验证码, v1.1.2-alph 版本已经内置, 具体配置可以看注释掉的 slider 配置
    customize:
      # 设置需要短信验证码认证的 uri(必须是非 GET 请求)，多个 uri 用 “，”号分开支持通配符，如：/hello,/user/*；默认为 /authentication/form
      auth-urls:
        - /authentication/form
        - /slider/check2
      # 提交验证码请求时，请求中带的验证码变量名，
      request-param-name: sliderToken

    # 滑块验证码, v1.1.2-alph 版本已经内置
    #slider:
    #  # 设置需要验证码认证的 uri(必须是非 GET 请求)，多个 uri 用 “-” 或 ","号分开支持通配符，如：/hello,/user/*；默认为 空
    #  auth-urls:
    #    - /authentication/form
    #  # 设置滑块验证码校验证的 uri, 默认: /slider/check, 默认: /slider/check
    #  slider-check-url: /slider/check
    #  # 提交验证码请求时，请求中带的验证码变量名，默认 sliderCode.
    #  # 与 tokenRequestParamName, xRequestParamName, yRequestParamName 互斥关系;
    #  # 当使用此参数时, 把另外三个参数(kv键值对形式, 键值对之间用逗号风隔) 组装到此参数.
    #  # 注意: 默认传递参数是用另外的三个参数实现验证码校验, 如要使用此参数, 请重新实现 ValidateCodeProcessor#validate(ServletWebRequest)
    #  request-param-name: sliderCode
    #  # request token param name, 默认: sliderToken. 与 requestParamName 互斥关系.
    #  token-request-param-name: sliderToken
    #  # request X param name, 默认: x. 与 requestParamName 互斥关系.
    #  x-request-param-name: x
    #  # request Y param name, 默认: y. 与 requestParamName 互斥关系.
    #  y-request-param-name: y
    #  # 抠图凸起圆心, 默认: 5
    #  circle-r: 5
    #  # 滑块图宽度, 默认: 50
    #  cut-width: 50
    #  # 滑块图高度, 默认: 50
    #  cut-height: 50
    #  # 抠图内部矩形填充大小, 默认: 8
    #  rectangle-padding:
    #  # 抠图的边框宽度, 默认:
    #  slider-img-out-padding:
    #  # 滑块验证码默认过期时间, 180 秒
    #  expire: 180
    #  # 原始图片目录，默认 static/image/validate/original
    #  original-image-directory: static/image/validate/original
    #  # 根据原始图片生成的滑块图片目录，用于自定义缓存滑块图片的存储目录, 默认 static/image/validate/template
    #  template-image-directory: static/image/validate/template


    # 短信验证码
    sms:
      # 设置需要短信验证码认证的 uri(必须是非 GET 请求)，多个 uri 用 “，”号分开支持通配符，如：/hello,/user/*；默认为 /authentication/form
      auth-urls:
        - /authentication/mobile
      length: 6
      expire: 120
      request-param-mobile-name: mobile
      request-param-sms-code-name: smsCode
  # ================ 手机登录配置 ================
  mobile:
    login:
      # 手机验证码登录是否开启, 默认 false，
      # 手机验证码登录开启后 必须配置 ums.codes.sms.auth-urls=/authentication/mobile
      sms-code-login-is-open: true
      # 手机验证码登录请求处理url, 默认 /authentication/mobile
      login-processing-url-mobile: /authentication/mobile

---
spring:
  profiles: dev
  mvc:
    throw-exception-if-no-handler-found: true

debug: true

logging:
  config: classpath:logback-spring.xml
